name: Deploy project
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run lint
        run: npm lint
      - name: Run test
        run: npm test
      - name: Deploy
        run: echo "Deploying...."
